language: cpp

dist: trusty

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y qtbase5-dev
    - sudo apt-get install -y libassimp-dev
    - sudo apt-get install -y libtinyxml2-dev
    - sudo apt-get install -y libjansson-dev

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

